### ISSUE TITLE
搞个docker 部署支持吧

### ISSUE THREAD

**Issue by Dev-Wiki** [sunzsh/internal-chat#10]

**Comment by Dev-Wiki** [comment]
大写的 谢谢~

**Comment by Ytv1** [comment]
+10086

**Comment by ai773203918** [comment]
docker pull 918178/internal-chat:latest
仅打包服务器端，配合Nginx部署，有非局域网设备可见问题(不可发送)
```
services:
  server:  # 服务器端WS
    image: 918178/internal-chat
    # ports:
      # - "8081:8081"  # 通过Nginx转发,无需开放

  nginx:  # Nginx 服务(客户端Web)
    image: nginx:latest  # 镜像名称
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx配置文件
      - ./www:/var/www/  # 静态文件
      - ./ssl:/etc/nginx/ssl/  # SSL证书
    ports:
      - "8443:8443"  # 客户端Web
  ```
